version: "3"

services:
  api:
    build: api
    ports: 
      - "3000:3000"
    depends_on:
      - db
  db:
    build: 
      db
    # needed to change the port Redis is running on as well as the exposed port.
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
    volumes:
      - ./data:/data